### ISSUE TITLE
handling modifications to or deletion of network drives/biases

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#248] opened 2021-01-20 19:06 UTC
Here's a place to resolve our discussion started in #221 about whether or not we should create formal methods in `Network` for modifying or deleting drive/bias attributes that have already been created.

As @ntolley pointed out, there is a common use case for modifying properties of a drive/bias after it has been added, attached, and possibly instantiated within a `Network` instance particularly if the user is running hnn-core using a jupyter notebook. In our example scripts, we also demonstrate ways that users can copy and modify properties of a given `Network` instance in order to rerun the simulation for different results. Regardless of whether or not we decide to expand the API, we should streamline our examples so that we either promote modification of existing (or copied) `Network` instances or solely promote the creation of new `Network` instances.

**Comment by jasmainak** [comment] 2021-01-20 19:21
duplicate of #235 ?

**Comment by rythorpe** [comment] 2021-01-21 02:56
Sure enough, I didn't see that one.

**Closed** 2021-01-21 02:56 UTC
